    - name: Wait for SSH
      ansible.builtin.wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
      connection: local

    - name: create partition
      become: true
      parted:
        device: /dev/xvdd
        number: 1
        flags: [ lvm ]
        state: present

    - name: Create volume group
      become: true
      community.general.lvg:
        vg: ai_wrk
        pvs: /dev/xvdd1
        pvresize: true
        state: active

    - name: Create volume
      become: true
      community.general.lvol:
        vg: ai_wrk
        lv: lv01
        size: +100%FREE #size: +500G
      register: lv
    - debug:
        msg: "{{ lv }}"

    - name: Is mount point
      stat:
        path: "{{ ai_wrk_dir }}"
      ignore_errors: true
      register: data
    - debug:
        msg: "{{ data }}"

    - name: Mount the volume
      become: true
      shell: |
        mkfs.ext4 /dev/ai_wrk/lv01
        mkdir /data0
        mount /dev/ai_wrk/lv01 /data0
        echo "/dev/ai_wrk/lv01  /data0  ext4  auto  0 0" >> /etc/fstab
        mkdir "{{ ai_wrk_dir }}"
        chown "{ my_user }:{ my_user }" "{{ ai_wrk_dir }}"
        chmod 0774 "{{ ai_wrk_dir }}"
      when: (data.stat.exists != true ) == true

